-- use this file to map the AP location ids to your locations
-- to reference a location in Pop use @ in the beginning and then path to the section (more info: https://github.com/black-sliver/PopTracker/blob/master/doc/PACKS.md#locations)
-- to reference an item use it's code
-- here are the SM locations as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/location_mapping.lua
LOCATION_MAPPING = {
--Start of Game
-- Geyser Rock
	[741000094] =  {"@Start Area - Geyser Rock and Sandover Region/Geyser Rock/Power Cell (Climb up the Cliff)"},
	[741000092] =  {"@Start Area - Geyser Rock and Sandover Region/Geyser Rock/Power Cell (Cell on the Path)"},
	[741000095] =  {"@Start Area - Geyser Rock and Sandover Region/Geyser Rock/Power Cell (7 Scout Flies)"},
	[741000093] =  {"@Start Area - Geyser Rock and Sandover Region/Geyser Rock/Power Cell (Open the Precursor Door)"},
	[741001759] =  {"@Start Area - Geyser Rock and Sandover Region/Geyser Rock/Scout Fly"},
	[741001119] =  {"@Start Area - Geyser Rock and Sandover Region/Geyser Rock/Scout Fly"},
	[741001887] =  {"@Start Area - Geyser Rock and Sandover Region/Geyser Rock/Scout Fly"},
	[741001631] =  {"@Start Area - Geyser Rock and Sandover Region/Geyser Rock/Scout Fly"},
	[741001375] =  {"@Start Area - Geyser Rock and Sandover Region/Geyser Rock/Scout Fly"},
	[741001247] =  {"@Start Area - Geyser Rock and Sandover Region/Geyser Rock/Scout Fly"},
	[741001503] =  {"@Start Area - Geyser Rock and Sandover Region/Geyser Rock/Scout Fly"},
--Sandover Region
--Sandover Village
	[741000013] =  {"@Start Area - Geyser Rock and Sandover Region/Sandover Village/Power Cell (120 Orbs to the Oracle)"},
	[741000014] =  {"@Start Area - Geyser Rock and Sandover Region/Sandover Village/Power Cell (120 Orbs to the Oracle)"},
	[741000011] =  {"@Start Area - Geyser Rock and Sandover Region/Sandover Village/Power Cell (90 Orbs to the Mayor)"},
	[741000012] =  {"@Start Area - Geyser Rock and Sandover Region/Sandover Village/Power Cell (90 Orbs to Your Uncle)"},
	[741000075] =  {"@Start Area - Geyser Rock and Sandover Region/Sandover Village/Power Cell (7 Scout Flies)"},
	[741000010] =  {"@Start Area - Geyser Rock and Sandover Region/Sandover Village/Power Cell (Herd the Yakows)"},
	[741004096] =  {"@Start Area - Geyser Rock and Sandover Region/Sandover Village/Orb Cache in Sandover Village (by Farmer's House)"},
	[741001227] =  {"@Start Area - Geyser Rock and Sandover Region/Sandover Village/Scout Fly (Behind Sculptor's House)"},
	[741001483] =  {"@Start Area - Geyser Rock and Sandover Region/Sandover Village/Scout Fly (Farmer's House)"},
	[741001611] =  {"@Start Area - Geyser Rock and Sandover Region/Sandover Village/Scout Fly (Fisherman's House)"},
	[741001739] =  {"@Start Area - Geyser Rock and Sandover Region/Sandover Village/Scout Fly (Mayor's House)"},
	[741001867] =  {"@Start Area - Geyser Rock and Sandover Region/Sandover Village/Scout Fly (Near Oracle)"},
	[741001099] =  {"@Start Area - Geyser Rock and Sandover Region/Sandover Village/Scout Fly (Overlooking Farmer's House)"},
	[741001355] =  {"@Start Area - Geyser Rock and Sandover Region/Sandover Village/Scout Fly (Under Bridge)"},
--Sentinel Beach
	[741000018] =  {"@Start Area - Geyser Rock and Sandover Region/Sentinel Beach/Power Cell (Chase the Seagulls)"},
	[741000022] =  {"@Start Area - Geyser Rock and Sandover Region/Sentinel Beach/Power Cell (Climb the Sentinel)"},
	[741000021] =  {"@Start Area - Geyser Rock and Sandover Region/Sentinel Beach/Power Cell (Explore the Beach)"},
	[741000020] =  {"@Start Area - Geyser Rock and Sandover Region/Sentinel Beach/Power Cell (7 Scout Flies)"},
	[741000016] =  {"@Start Area - Geyser Rock and Sandover Region/Sentinel Beach/Power Cell (Get the Power Cell from the Pelican)"},
	[741000019] =  {"@Start Area - Geyser Rock and Sandover Region/Sentinel Beach/Power Cell (Launch up to the Cannon Tower)"},
	[741000015] =  {"@Start Area - Geyser Rock and Sandover Region/Sentinel Beach/Power Cell (Unblock the Eco Harvesters)"},
	[741000017] =  {"@Start Area - Geyser Rock and Sandover Region/Sentinel Beach/Power Cell (Push the Flut Flut Egg)"},
	[741002065] =  {"@Start Area - Geyser Rock and Sandover Region/Sentinel Beach/Flut Flut (Push the Flut Flut Egg)"},
	[741006386] =  {"@Start Area - Geyser Rock and Sandover Region/Sentinel Beach/Orb Cache by the Flut Flut Egg"},
	[741006387] =  {"@Start Area - Geyser Rock and Sandover Region/Sentinel Beach/Orb Cache by the Pelican's Nest"},
	[741001684] =  {"@Start Area - Geyser Rock and Sandover Region/Sentinel Beach/Scout Fly (Entrance)"},
	[741001172] =  {"@Start Area - Geyser Rock and Sandover Region/Sentinel Beach/Scout Fly (Path to Flut Flut)"},
	[741001812] =  {"@Start Area - Geyser Rock and Sandover Region/Sentinel Beach/Scout Fly (Sentinel)"},
	[741001428] =  {"@Start Area - Geyser Rock and Sandover Region/Sentinel Beach/Scout Fly (Overlooking Blue Eco Vent)"},
	[741001300] =  {"@Start Area - Geyser Rock and Sandover Region/Sentinel Beach/Scout Fly (Overlooking Green Eco Vents)"},
	[741001044] =  {"@Start Area - Geyser Rock and Sandover Region/Sentinel Beach/Scout Fly (Overlooking Locked Boxes)"},
	[741001556] =  {"@Start Area - Geyser Rock and Sandover Region/Sentinel Beach/Scout Fly (Under Wood Pillars)"},
--Forbidden Jungle
	[741000005] =  {"@Start Area - Geyser Rock and Sandover Region/Forbidden Jungle/Power Cell (Catch 200 lbs of Fish)"},
	[741002053] =  {"@Start Area - Geyser Rock and Sandover Region/Forbidden Jungle/Boat Keys (Catch 200 lbs of Fish)"},
	[741000003] =  {"@Start Area - Geyser Rock and Sandover Region/Forbidden Jungle/Power Cell (Connect the Eco Beams)"},
	[741000006] =  {"@Start Area - Geyser Rock and Sandover Region/Forbidden Jungle/Power Cell (Defeat the Dark Eco Plant)"},
	[741000002] =  {"@Start Area - Geyser Rock and Sandover Region/Forbidden Jungle/Power Cell (Find the Blue Vent Switch)"},
	[741002050] =  {"@Start Area - Geyser Rock and Sandover Region/Forbidden Jungle/Blue Eco Switch"},
	[741000008] =  {"@Start Area - Geyser Rock and Sandover Region/Forbidden Jungle/Power Cell (Follow the Canyon to the Sea)"},
	[741000007] =  {"@Start Area - Geyser Rock and Sandover Region/Forbidden Jungle/Power Cell (7 Scout Flies)"},
	[741000004] =  {"@Start Area - Geyser Rock and Sandover Region/Forbidden Jungle/Power Cell (Get to the Top of the Temple)"},
	[741002052] =  {"@Start Area - Geyser Rock and Sandover Region/Forbidden Jungle/Jungle Elevator"},
	[741000009] =  {"@Start Area - Geyser Rock and Sandover Region/Forbidden Jungle/Power Cell (Open the Locked Temple Door)"},
	[741004121] =  {"@Start Area - Geyser Rock and Sandover Region/Forbidden Jungle/Orb Cache in Forbidden Jungle (River)"},
	[741001671] =  {"@Start Area - Geyser Rock and Sandover Region/Forbidden Jungle/Scout Fly (Around Temple Spire)"},
	[741001799] =  {"@Start Area - Geyser Rock and Sandover Region/Forbidden Jungle/Scout Fly (End of Path)"},
	[741001415] =  {"@Start Area - Geyser Rock and Sandover Region/Forbidden Jungle/Scout Fly (End of River)"},
	[741001287] =  {"@Start Area - Geyser Rock and Sandover Region/Forbidden Jungle/Scout Fly (Behind Lurker Machine)"},
	[741001031] =  {"@Start Area - Geyser Rock and Sandover Region/Forbidden Jungle/Scout Fly (Near Dark Eco Boxes (River))"},
	[741001543] =  {"@Start Area - Geyser Rock and Sandover Region/Forbidden Jungle/Scout Fly (Spiral of Stumps)"},
	[741001159] =  {"@Start Area - Geyser Rock and Sandover Region/Forbidden Jungle/Scout Fly (Top of Temple)"},	
--Misty Island
	[741000023] =  {"@Misty Island/Misty Island/Power Cell (Catch the Sculptor's Muse)"},
	[741000024] =  {"@Misty Island/Misty Island/Power Cell (Climb the Lurker Ship)"},
	[741000027] =  {"@Misty Island/Misty Island/Power Cell (Destroy Balloon Lurkers)"},
	[741000028] =  {"@Misty Island/Misty Island/Power Cell (7 Scout Flies)"},
	[741000025] =  {"@Misty Island/Misty Island/Power Cell (Dark Eco Pool)"},
	[741000026] =  {"@Misty Island/Misty Island/Power Cell (Stop the Cannon)"},
	[741000030] =  {"@Misty Island/Misty Island/Power Cell (Blue Eco Power Cell)"},
	[741000029] =  {"@Misty Island/Misty Island/Power Cell (Zoomer Power Cell)"},
	[741004824] =  {"@Misty Island/Misty Island/Orb Cache on Misty Island (Near Arena Exit)"},
	[741001564] =  {"@Misty Island/Misty Island/Scout Fly (Near Arena Door)"},
	[741001436] =  {"@Misty Island/Misty Island/Scout Fly (Barrel Ramps)"},
	[741001180] =  {"@Misty Island/Misty Island/Scout Fly (Ledge Near Arena Entrance)"},
	[741001052] =  {"@Misty Island/Misty Island/Scout Fly (Ledge Near Arena Exit)"},
	[741001308] =  {"@Misty Island/Misty Island/Scout Fly (Ship)"},
	[741001820] =  {"@Misty Island/Misty Island/Scout Fly (Zoomer Ramps)"},
	[741001692] =  {"@Misty Island/Misty Island/Scout Fly (Overlooking Entrance)"},
--Fire Canyon	
	[741000068] =  {"@Fire Canyon/Fire Canyon/Power Cell (7 Scout Flies)"},
	[741000069] =  {"@Fire Canyon/Fire Canyon/Power Cell (Reach the End of Fire Canyon)"},
	[741001860] =  {"@Fire Canyon/Fire Canyon/Scout Fly"},
	[741001092] =  {"@Fire Canyon/Fire Canyon/Scout Fly"},
	[741001220] =  {"@Fire Canyon/Fire Canyon/Scout Fly"},
	[741001476] =  {"@Fire Canyon/Fire Canyon/Scout Fly"},
	[741001348] =  {"@Fire Canyon/Fire Canyon/Scout Fly"},
	[741001604] =  {"@Fire Canyon/Fire Canyon/Scout Fly"},
	[741001732] =  {"@Fire Canyon/Fire Canyon/Scout Fly"},
--Rock Village Region
--Rock Village
	[741000034] =  {"@Secondary Area - Rock Village Region/Rock Village/Power Cell (120 Orbs to the Oracle)"},
	[741000035] =  {"@Secondary Area - Rock Village Region/Rock Village/Power Cell (120 Orbs to the Oracle)"},
	[741000031] =  {"@Secondary Area - Rock Village Region/Rock Village/Power Cell (90 Orbs to the Gambler)"},
	[741000032] =  {"@Secondary Area - Rock Village Region/Rock Village/Power Cell (90 Orbs to the Geologist)"},
	[741000033] =  {"@Secondary Area - Rock Village Region/Rock Village/Power Cell (90 Orbs to the Warrior)"},
	[741000076] =  {"@Secondary Area - Rock Village Region/Rock Village/Power Cell (7 Scout Flies)"},
	[741002081] =  {"@Secondary Area - Rock Village Region/Rock Village/Warrior's Pontoons"},
	[741004697] =  {"@Secondary Area - Rock Village Region/Rock Village/Orb Cache in Rock Village (by Oracle)"},
	[741001868] =  {"@Secondary Area - Rock Village Region/Rock Village/Scout Fly (Boggy Swamp Entrance)"},
	[741001740] =  {"@Secondary Area - Rock Village Region/Rock Village/Scout Fly (Pontoon Bridge)"},
	[741001612] =  {"@Secondary Area - Rock Village Region/Rock Village/Scout Fly (Behind Fiery Boulder)"},
	[741001484] =  {"@Secondary Area - Rock Village Region/Rock Village/Scout Fly (Behind Geologist)"},
	[741001100] =  {"@Secondary Area - Rock Village Region/Rock Village/Scout Fly (Behind Sage's Hut)"},
	[741001356] =  {"@Secondary Area - Rock Village Region/Rock Village/Scout Fly (Near Waterfall)"},
	[741001228] =  {"@Secondary Area - Rock Village Region/Rock Village/Scout Fly (Dock)"},
--Lost Precursor City
	[741000050] =  {"@Secondary Area - Rock Village Region/Lost Precursor City/Power Cell (Climb the Slide Tube)"},
	[741000045] =  {"@Secondary Area - Rock Village Region/Lost Precursor City/Power Cell (Follow the Colored Pipes)"},
	[741000049] =  {"@Secondary Area - Rock Village Region/Lost Precursor City/Power Cell (7 Scout Flies)"},
	[741000044] =  {"@Secondary Area - Rock Village Region/Lost Precursor City/Power Cell (Match the Platform Colors)"},
	[741000048] =  {"@Secondary Area - Rock Village Region/Lost Precursor City/Power Cell (Quickly Cross the Dangerous Pool)"},
	[741000047] =  {"@Secondary Area - Rock Village Region/Lost Precursor City/Power Cell (Raise the Chamber)"},
	[741000046] =  {"@Secondary Area - Rock Village Region/Lost Precursor City/Power Cell (Reach the Bottom of the City)"},
	[741000051] =  {"@Secondary Area - Rock Village Region/Lost Precursor City/Power Cell (Reach the Center of the Complex)"},
	[741008259] =  {"@Secondary Area - Rock Village Region/Lost Precursor City/Orb Cache First Sunken Chamber"},
	[741008590] =  {"@Secondary Area - Rock Village Region/Lost Precursor City/Orb Cache Second Sunken Chamber"},
	[741001713] =  {"@Secondary Area - Rock Village Region/Lost Precursor City/Scout Fly (Across Steam Vents)"},
	[741001329] =  {"@Secondary Area - Rock Village Region/Lost Precursor City/Scout Fly (Before Second Room)"},
	[741001585] =  {"@Secondary Area - Rock Village Region/Lost Precursor City/Scout Fly (First Room)"},
	[741001201] =  {"@Secondary Area - Rock Village Region/Lost Precursor City/Scout Fly (Second Room, Blue Pipe)"},
	[741001073] =  {"@Secondary Area - Rock Village Region/Lost Precursor City/Scout Fly (Second Room, Green Pipe)"},
	[741001841] =  {"@Secondary Area - Rock Village Region/Lost Precursor City/Scout Fly (Second Room, Near Orb Vent)"},
	[741001457] =  {"@Secondary Area - Rock Village Region/Lost Precursor City/Scout Fly (Second Room, on Path to Cell)"},
--Boggy Swamp
	[741000039] =  {"@Secondary Area - Rock Village Region/Boggy Swamp/Power Cell (Break the Zeppelin Tether 1)"},
	[741000040] =  {"@Secondary Area - Rock Village Region/Boggy Swamp/Power Cell (Break the Zeppelin Tether 2)"},
	[741000041] =  {"@Secondary Area - Rock Village Region/Boggy Swamp/Power Cell (Break the Zeppelin Tether 3)"},
	[741000042] =  {"@Secondary Area - Rock Village Region/Boggy Swamp/Power Cell (Break the Zeppelin Tether 4)"},
	[741000038] =  {"@Secondary Area - Rock Village Region/Boggy Swamp/Power Cell (Defeat the Lurker Ambush)"},
	[741000043] =  {"@Secondary Area - Rock Village Region/Boggy Swamp/Power Cell (7 Scout Flies)"},
	[741000036] =  {"@Secondary Area - Rock Village Region/Boggy Swamp/Power Cell (Protect Farthy's Snacks)"},
	[741000037] =  {"@Secondary Area - Rock Village Region/Boggy Swamp/Power Cell (Ride the Flut Flut)"},
	[741001579] =  {"@Secondary Area - Rock Village Region/Boggy Swamp/Scout Fly (Across Black Swamp)"},
	[741001451] =  {"@Secondary Area - Rock Village Region/Boggy Swamp/Scout Fly (in Field of Boxes)"},
	[741001067] =  {"@Secondary Area - Rock Village Region/Boggy Swamp/Scout Fly (Near Entrance)"},
	[741001323] =  {"@Secondary Area - Rock Village Region/Boggy Swamp/Scout Fly (on Flut Flut Platforms)"},
	[741001835] =  {"@Secondary Area - Rock Village Region/Boggy Swamp/Scout Fly (Over First Jump Pad)"},
	[741001195] =  {"@Secondary Area - Rock Village Region/Boggy Swamp/Scout Fly (Over Second Jump Pad)"},
	[741001707] =  {"@Secondary Area - Rock Village Region/Boggy Swamp/Scout Fly (Overlooking Flut Flut)"},
--Precursor Basin
	[741000052] =  {"@Secondary Area - Rock Village Region/Precursor Basin/Power Cell (Beat the Gorge Record Time)"},
	[741000053] =  {"@Secondary Area - Rock Village Region/Precursor Basin/Power Cell (Catch the Flying Lurkers)"},
	[741000055] =  {"@Secondary Area - Rock Village Region/Precursor Basin/Power Cell (Cure Dark Eco Infected Plants)"},
	[741000057] =  {"@Secondary Area - Rock Village Region/Precursor Basin/Power Cell (7 Scout Flies)"},
	[741000056] =  {"@Secondary Area - Rock Village Region/Precursor Basin/Power Cell (Get the Power Cell Over the Lake)"},
	[741000054] =  {"@Secondary Area - Rock Village Region/Precursor Basin/Power Cell (Herd the Moles)"},
	[741000059] =  {"@Secondary Area - Rock Village Region/Precursor Basin/Power Cell (Navigate the Blue Precursor Rings)"},
	[741000058] =  {"@Secondary Area - Rock Village Region/Precursor Basin/Power Cell (Navigate the Purple Precursor Rings)"},
	[741001081] =  {"@Secondary Area - Rock Village Region/Precursor Basin/Scout Fly"},
	[741001337] =  {"@Secondary Area - Rock Village Region/Precursor Basin/Scout Fly"},
	[741001593] =  {"@Secondary Area - Rock Village Region/Precursor Basin/Scout Fly"},
	[741001209] =  {"@Secondary Area - Rock Village Region/Precursor Basin/Scout Fly"},
	[741001721] =  {"@Secondary Area - Rock Village Region/Precursor Basin/Scout Fly"},
	[741001849] =  {"@Secondary Area - Rock Village Region/Precursor Basin/Scout Fly"},
	[741001465] =  {"@Secondary Area - Rock Village Region/Precursor Basin/Scout Fly"},
--Klaww
	[741000086] =  {"@Klaww/Klaww/Power Cell (Defeat Klaww)"},
--Mountain Pass	
	[741000110] =  {"@Mountain Pass/Mountain Pass/Power Cell (Find the Hidden Power Cell)"},
	[741000088] =  {"@Mountain Pass/Mountain Pass/Power Cell (7 Scout Flies)"},
	[741000087] =  {"@Mountain Pass/Mountain Pass/Power Cell (Reach the End of Mountain Pass)"},
	[741001112] =  {"@Mountain Pass/Mountain Pass/Scout Fly"},
	[741001240] =  {"@Mountain Pass/Mountain Pass/Scout Fly"},
	[741001368] =  {"@Mountain Pass/Mountain Pass/Scout Fly"},
	[741001496] =  {"@Mountain Pass/Mountain Pass/Scout Fly"},
	[741001624] =  {"@Mountain Pass/Mountain Pass/Scout Fly"},
	[741001752] =  {"@Mountain Pass/Mountain Pass/Scout Fly"},
	[741001880] =  {"@Mountain Pass/Mountain Pass/Scout Fly"},
--Volcanic Crater Region
--Volcanic Crater
	[741000100] =  {"@Tertiary Area - Volcanic Crater Region/Volcanic Crater/Power Cell (120 Orbs to the Oracle)"},
	[741000101] =  {"@Tertiary Area - Volcanic Crater Region/Volcanic Crater/Power Cell (120 Orbs to the Oracle)"},
	[741000096] =  {"@Tertiary Area - Volcanic Crater Region/Volcanic Crater/Power Cell (90 Orbs to the Miners)"},
	[741000097] =  {"@Tertiary Area - Volcanic Crater Region/Volcanic Crater/Power Cell (90 Orbs to the Miners)"},
	[741000098] =  {"@Tertiary Area - Volcanic Crater Region/Volcanic Crater/Power Cell (90 Orbs to the Miners)"},
	[741000099] =  {"@Tertiary Area - Volcanic Crater Region/Volcanic Crater/Power Cell (90 Orbs to the Miners)"},
	[741000074] =  {"@Tertiary Area - Volcanic Crater Region/Volcanic Crater/Power Cell (Find the Hidden Power Cell)"},
	[741000077] =  {"@Tertiary Area - Volcanic Crater Region/Volcanic Crater/Power Cell (7 Scout Flies)"},
	[741001101] =  {"@Tertiary Area - Volcanic Crater Region/Volcanic Crater/Scout Fly"},
	[741001613] =  {"@Tertiary Area - Volcanic Crater Region/Volcanic Crater/Scout Fly"},
	[741001357] =  {"@Tertiary Area - Volcanic Crater Region/Volcanic Crater/Scout Fly"},
	[741001741] =  {"@Tertiary Area - Volcanic Crater Region/Volcanic Crater/Scout Fly"},
	[741001869] =  {"@Tertiary Area - Volcanic Crater Region/Volcanic Crater/Scout Fly"},
	[741001229] =  {"@Tertiary Area - Volcanic Crater Region/Volcanic Crater/Scout Fly"},
	[741001485] =  {"@Tertiary Area - Volcanic Crater Region/Volcanic Crater/Scout Fly"},
--Spider Cave
	[741000081] =  {"@Tertiary Area - Volcanic Crater Region/Spider Cave/Power Cell (Climb the Giant Robot)"},
	[741000084] =  {"@Tertiary Area - Volcanic Crater Region/Spider Cave/Power Cell (Climb the Precursor Platforms)"},
	[741000079] =  {"@Tertiary Area - Volcanic Crater Region/Spider Cave/Power Cell (Destroy the Dark Eco Crystals)"},
	[741000080] =  {"@Tertiary Area - Volcanic Crater Region/Spider Cave/Power Cell (Explore the Dark Cave)"},
	[741000085] =  {"@Tertiary Area - Volcanic Crater Region/Spider Cave/Power Cell (7 Scout Flies)"},
	[741000082] =  {"@Tertiary Area - Volcanic Crater Region/Spider Cave/Power Cell (Launch to the Poles)"},
	[741000083] =  {"@Tertiary Area - Volcanic Crater Region/Spider Cave/Power Cell (Navigate the Spider Tunnel)"},
	[741000078] =  {"@Tertiary Area - Volcanic Crater Region/Spider Cave/Power Cell (Shoot the Gnawing Lurkers)"},
	[741001621] =  {"@Tertiary Area - Volcanic Crater Region/Spider Cave/Scout Fly (Dark Cave)"},
	[741001493] =  {"@Tertiary Area - Volcanic Crater Region/Spider Cave/Scout Fly (Main Cave, Near Dark Crystal)"},
	[741001365] =  {"@Tertiary Area - Volcanic Crater Region/Spider Cave/Scout Fly (Main Cave, Near Robot Cave Entrance)"},
	[741001877] =  {"@Tertiary Area - Volcanic Crater Region/Spider Cave/Scout Fly (Main Cave, Overlooking Entrance)"},
	[741001749] =  {"@Tertiary Area - Volcanic Crater Region/Spider Cave/Scout Fly (Near Dark Cave Entrance)"},
	[741001109] =  {"@Tertiary Area - Volcanic Crater Region/Spider Cave/Scout Fly (Robot Cave, at Bottom Level)"},
	[741001237] =  {"@Tertiary Area - Volcanic Crater Region/Spider Cave/Scout Fly (Robot Cave, at Top Level)"},
--Snowy Mountain
	[741002153] =  {"@Tertiary Area - Volcanic Crater Region/Snowy Mountain/Snowy Mountain Gondola"},
	[741000066] =  {"@Tertiary Area - Volcanic Crater Region/Snowy Mountain/Power Cell (Deactivate the Precursor Blockers)"},
	[741000060] =  {"@Tertiary Area - Volcanic Crater Region/Snowy Mountain/Power Cell (Find the Yellow Vent Switch)"},
	[741002108] =  {"@Tertiary Area - Volcanic Crater Region/Snowy Mountain/Yellow Eco Switch"},
	[741000065] =  {"@Tertiary Area - Volcanic Crater Region/Snowy Mountain/Power Cell (7 Scout Flies)"},
	[741000062] =  {"@Tertiary Area - Volcanic Crater Region/Snowy Mountain/Power Cell (Get Through the Lurker Fort)"},
	[741000067] =  {"@Tertiary Area - Volcanic Crater Region/Snowy Mountain/Power Cell (Open the Frozen Crate)"},
	[741000063] =  {"@Tertiary Area - Volcanic Crater Region/Snowy Mountain/Power Cell (Open the Lurker Fort Gate)"},
	[741002111] =  {"@Tertiary Area - Volcanic Crater Region/Snowy Mountain/Open the Lurker Fort Gate"},
	[741000061] =  {"@Tertiary Area - Volcanic Crater Region/Snowy Mountain/Power Cell (Stop the 3 Lurker Glacier Troops)"},
	[741000064] =  {"@Tertiary Area - Volcanic Crater Region/Snowy Mountain/Power Cell (Survive the Lurker Infested Cave)"},
	[741017100] =  {"@Tertiary Area - Volcanic Crater Region/Snowy Mountain/Orb Cache in Snowy Fort"},
	[741017101] =  {"@Tertiary Area - Volcanic Crater Region/Snowy Mountain/Orb Cache in Snowy Fort"},
	[741017102] =  {"@Tertiary Area - Volcanic Crater Region/Snowy Mountain/Orb Cache in Snowy Fort"},
	[741001089] =  {"@Tertiary Area - Volcanic Crater Region/Snowy Mountain/Scout Fly (Near Entrance)"},
	[741001729] =  {"@Tertiary Area - Volcanic Crater Region/Snowy Mountain/Scout Fly (Near Frozen Box)"},
	[741001217] =  {"@Tertiary Area - Volcanic Crater Region/Snowy Mountain/Scout Fly (Near Yellow Eco Switch)"},
	[741001345] =  {"@Tertiary Area - Volcanic Crater Region/Snowy Mountain/Scout Fly (Cliff Near Flut Flut)"},
	[741001601] =  {"@Tertiary Area - Volcanic Crater Region/Snowy Mountain/Scout Fly (Top of Fort)"},
	[741001473] =  {"@Tertiary Area - Volcanic Crater Region/Snowy Mountain/Scout Fly (Top of Fort Tower)"},
	[741001857] =  {"@Tertiary Area - Volcanic Crater Region/Snowy Mountain/Scout Fly (Under Bridge to Fort)"},
--Lava Tube	
	[741000089] =  {"@Lava Tube/Lava Tube/Power Cell (Reach the End of Lava Tube)"},
	[741000090] =  {"@Lava Tube/Lava Tube/Power Cell (7 Scout Flies)"},
	[741001114] =  {"@Lava Tube/Lava Tube/Scout Fly"},
	[741001242] =  {"@Lava Tube/Lava Tube/Scout Fly"},
	[741001754] =  {"@Lava Tube/Lava Tube/Scout Fly"},
	[741001626] =  {"@Lava Tube/Lava Tube/Scout Fly"},
	[741001370] =  {"@Lava Tube/Lava Tube/Scout Fly"},
	[741001498] =  {"@Lava Tube/Lava Tube/Scout Fly"},
	[741001882] =  {"@Lava Tube/Lava Tube/Scout Fly"},
--Gol and Maia's Citadel
	[741000091] =  {"@Gol and Maia's Citadel/Gol and Maia's Citadel/Power Cell (7 Scout Flies)"},
	[741000071] =  {"@Gol and Maia's Citadel/Gol and Maia's Citadel/Power Cell (Free the Blue Sage)"},
	[741002119] =  {"@Gol and Maia's Citadel/Gol and Maia's Citadel/Blue Sage Freed"},
	[741000070] =  {"@Gol and Maia's Citadel/Gol and Maia's Citadel/Power Cell (Free the Green Sage)"},
	[741002118] =  {"@Gol and Maia's Citadel/Gol and Maia's Citadel/Green Sage Freed"},
	[741000072] =  {"@Gol and Maia's Citadel/Gol and Maia's Citadel/Power Cell (Free the Red Sage)"},
	[741002120] =  {"@Gol and Maia's Citadel/Gol and Maia's Citadel/Red Sage Freed"},
	[741000073] =  {"@Gol and Maia's Citadel/Gol and Maia's Citadel/Power Cell (Free the Yellow Sage)"},
	[741002121] =  {"@Gol and Maia's Citadel/Gol and Maia's Citadel/Yellow Sage Freed"},
	[741001883] =  {"@Gol and Maia's Citadel/Gol and Maia's Citadel/Scout Fly (Blast Furnace)"},
	[741001115] =  {"@Gol and Maia's Citadel/Gol and Maia's Citadel/Scout Fly (Entrance)"},
	[741001371] =  {"@Gol and Maia's Citadel/Gol and Maia's Citadel/Scout Fly (Launch Pad Room)"},
	[741001627] =  {"@Gol and Maia's Citadel/Gol and Maia's Citadel/Scout Fly (Before Jumping Lurkers)"},
	[741001243] =  {"@Gol and Maia's Citadel/Gol and Maia's Citadel/Scout Fly (Main Room, Left of Robot)"},
	[741001499] =  {"@Gol and Maia's Citadel/Gol and Maia's Citadel/Scout Fly (Main Room, Right of Robot)"},
	[741001755] =  {"@Gol and Maia's Citadel/Gol and Maia's Citadel/Scout Fly (Top of Rotating Tower)"},
}
